#include "SetupParameter.h"

void Setup()
{
    //GPIO Configurations
    //INPUTS
    CLR_BIT(DDRD,PD2);
    SET_BIT(PORTD,PD2);
    CLR_BIT(DDRC,PC0);
    SET_BIT(PORTC,PC0);
    CLR_BIT(DDRC,PC5);
    SET_BIT(PORTC,PC5);
    CLR_BIT(DDRB,PB5);
    SET_BIT(PORTB,PB5);
    CLR_BIT(DDRC,PC6);
    SET_BIT(PORTC,PC6);
    CLR_BIT(DDRD,PD3);
    SET_BIT(PORTD,PD3);

    // OUTPUTS
    SET_BIT(DDRB,PB1);
    CLR_BIT(PORTB,PB1);
    SET_BIT(DDRB,PB2);
    CLR_BIT(PORTB,PB2);
    SET_BIT(DDRB,PB3);
    CLR_BIT(PORTB,PB3);

    //INTERRUPT CONFIGURATION
    SET_BIT(SREG,7);
    SET_BIT(EICRA,ISC00);
    SET_BIT(EICRA,ISC01);
    SET_BIT(EIMSK,INT0);
    SET_BIT(EICRA,ISC10);
    SET_BIT(EICRA,ISC11);
    SET_BIT(EIMSK,INT1);
    SET_BIT(PCICR,PCIE1);
    SET_BIT(PCMSK1,PCINT14);

    //ADC CONFIGURATIONS'
    CLR_BIT(ADCSRA,ADEN);
}
